title: Gap Filler Labs
description: Where problems find their missing piece!
theme: just-the-docs

url: https://gapfillerlabs.github.io/

aux_links:
  Gap Filler Labs on Github: https://github.com/gapfillerlabs/
aux_links_new_tab: true

collections:
  # Define a collection named "ingestor", its documents reside in the "_ingestor" directory
  ingestor:
    permalink: "/:collection/:path/"
    output: true
  bpmn_collab:
    permalink: "/:collection/:path/"
    output: true
  pixel_pointer:
    permalink: "/:collection/:path/"
    output: true
just_the_docs:
  # Define which collections are used in just-the-docs
  collections:
    ingestor:
      name: Ingestor
    bpmn_collab:
      name: BPMN Collab
    pixel_pointer:
      name: Pixel Pointer
    unified_automation_document:
      name: Unified Automation Document
    
