title: Gap Filler Labs
description: Where problems find their missing piece!
theme: just-the-docs

url: https://gapfillerlabs.github.io/

aux_links:
  Gap Filler Labs on Github: https://gapfillerlabs.github.io/
aux_links_new_tab: false

collections:
  # Define a collection named "tests", its documents reside in the "_ingestor" directory
  ingestor:
    permalink: "/:collection/:path/"
    output: true
just_the_docs:
  # Define which collections are used in just-the-docs
  collections:
    # Reference the "tests" collection
    ingestor:
      # Give the collection a name
      name: Ingestor
